theme = "identity"
disableKinds = ['taxonomy', 'term']
copyright = "2023 プロフィール.com"

baseURL = "https://xn--dck5ef6fh6g.com/lifa/"
title = "Lifa | プロフィール.com"

[params]
author = "Lifa"
icon = "lifa"
description = "Backend Engineer"

[[params.social]]
name = "twitter"
icon = "brands fa-twitter"
url = "https://twitter.com/intent/user?user_id=1597757894774362114"
